---
galaxy_info:
  author: Saint-Pablo-3
  description: "Ansible role to install and configure Vector (vector.dev)"
  company: "YourCompany"
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
dependencies: []


