---
vector_version: "0.20.0"
vector_download_url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}.rpm"
vector_service_name: "vector"
vector_config_path: "/etc/vector/vector.toml"

#SPDX-License-Identifier: MIT-0
---
# defaults file for vector-role
